ASTRA_DB_APPLICATION_TOKEN=''
ASTRA_DB_DATABASE_ID=''
ASTRA_DB_REGION='ap-south-1'
ASTRA_DB_NAMESPACE='default_keyspace'
OPENAI_API_KEY=''
ASTRA_DB_ENDPOINT=''
ASTRA_DB_API_ENDPOINT=''

LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""

